#!/bin/bash
# gen-sm-key

NODE_KEY=deadbeefcafebabe
VENDOR_ID=1234
SM=dummy

VENDOR_KEY=$(sancus-crypto --key $NODE_KEY --gen-vendor-key $VENDOR_ID | xxd -p)
sancus-crypto --key $VENDOR_KEY --fill-macs -o main.elf main.elf-no-macs
sancus-crypto --gen-sm-key $SM --key $VENDOR_KEY main.elf



